import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity,AlertCircle,ArrowUpRight,CheckCircle2,ChevronRight,Fingerprint,LayoutDashboard,Menu,Network,Plus,Search,Shield,ShieldAlert,Siren,X,Zap,FileDown} from 'lucide-react';
import {Area,AreaChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import './styles.css';
const API=import.meta.env.VITE_API_URL||'http://localhost:8000', WS=import.meta.env.VITE_WS_URL||'ws://localhost:8000';
const api=async(path,opt={})=>{let r=await fetch(API+path,{headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});if(!r.ok){let d='Request failed';try{d=(await r.json()).detail||d}catch{}throw Error(d)};let t=r.headers.get('content-type')||'';return t.includes('application/json')?r.json():r.text()};
const nav=[['dashboard','Overview',LayoutDashboard],['alerts','Alerts',ShieldAlert],['incidents','Incidents',Siren],['iocs','IOC Intel',Fingerprint]];
const fmt=v=>v?new Date(v).toLocaleString([],{month:'short',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'—';
function App(){const[page,setPage]=useState('dashboard'),[stats,setStats]=useState(null),[alerts,setAlerts]=useState([]),[inc,setInc]=useState([]),[drawer,setDrawer]=useState(null),[toast,setToast]=useState(null),[mobile,setMobile]=useState(false);
const refresh=async()=>{try{let[s,a,i]=await Promise.all([api('/api/stats'),api('/api/alerts'),api('/api/incidents')]);setStats(s);setAlerts(a);setInc(i)}catch(e){show(e.message,'error')}};
const show=(m,t='success')=>{setToast({m,t});setTimeout(()=>setToast(null),2800)};
useEffect(()=>{refresh();let timer=setInterval(refresh,10000),ws;try{ws=new WebSocket(WS+'/ws/alerts');ws.onopen=()=>ws.send('subscribe');ws.onmessage=e=>{let m=JSON.parse(e.data);refresh();if(m.type==='new_alert')show('New security alert detected')}}catch{}return()=>{clearInterval(timer);ws?.close()}},[]);
async function gen(kind){try{let p=await api('/api/demo/generate-alert?kind='+kind,{method:'POST'});await refresh();setDrawer({type:'alert',data:p.alert});show('Synthetic detection generated')}catch(e){show(e.message,'error')}}
async function openAlert(id){try{setDrawer({type:'alert',data:await api('/api/alerts/'+id)})}catch(e){show(e.message,'error')}}
async function openIncident(id){try{setDrawer({type:'incident',data:await api('/api/incidents/'+id)})}catch(e){show(e.message,'error')}}
const content=page==='dashboard'?<Dashboard stats={stats} alerts={alerts} inc={inc} openAlert={openAlert} openIncident={openIncident} gen={gen}/>:page==='alerts'?<Alerts alerts={alerts} openAlert={openAlert}/>:page==='incidents'?<Incidents inc={inc} open={openIncident}/>:<IOCs show={show}/>;
return <div className="shell"><aside className={'side '+(mobile?'open':'')}><div className="brand"><span className="brandIcon"><Shield size={20}/></span><div><b>SOCX</b><small>Security Operations Center</small></div></div><nav>{nav.map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>{setPage(id);setMobile(false)}}><Icon size={17}/><span>{label}</span>{id==='alerts'&&stats?.total_alerts?<em>{stats.total_alerts}</em>:null}</button>)}</nav><div className="sideBottom"><span className="online"><i/>Detection engine online</span><small>SOCX v1.0 · Lab Mode</small></div></aside>
<main className="main"><header className="top"><button className="menu" onClick={()=>setMobile(!mobile)}><Menu size={20}/></button><div><small>SECURITY OPERATIONS</small><h1>{({dashboard:'SOC Overview',alerts:'Alert Queue',incidents:'Incident Response',iocs:'IOC Intelligence'})[page]}</h1></div><button className="ghost" onClick={()=>gen('ssh')}><Zap size={15}/> Test Detection</button></header><div className="content">{content}</div></main>
{drawer?.type==='alert'&&<AlertDrawer a={drawer.data} close={()=>setDrawer(null)} refresh={refresh} show={show} create={async()=>{let i=await api('/api/incidents',{method:'POST',body:JSON.stringify({alert_id:drawer.data.id,assigned_to:'SOC Analyst',summary:`Investigation opened for ${drawer.data.title}. Source ${drawer.data.source_ip||'N/A'}.`})});await refresh();setDrawer({type:'incident',data:i});show(i.incident_id+' created')}}/>}
{drawer?.type==='incident'&&<IncidentDrawer i={drawer.data} close={()=>setDrawer(null)} refresh={refresh} show={show}/>} {toast&&<div className={'toast '+toast.t}>{toast.t==='error'?<AlertCircle size={16}/>:<CheckCircle2 size={16}/>} {toast.m}</div>}</div>}
function Dashboard({stats,alerts,inc,openAlert,openIncident,gen}){if(!stats)return <Loading/>;return <div className="stack"><section className="hero"><div><p>Live telemetry and analyst workflow</p><h2>Threat visibility at a glance.</h2></div><div className="actions"><button onClick={()=>gen('ssh')}>SSH Brute Force</button><button onClick={()=>gen('scan')}>Port Scan</button><button onClick={()=>gen('powershell')}>PowerShell</button></div></section><div className="metrics"><Metric t="Critical" v={stats.critical} d="Immediate triage"/><Metric t="High" v={stats.high} d="High-priority risk"/><Metric t="Medium" v={stats.medium} d="Analyst review"/><Metric t="Open Incidents" v={stats.open_incidents} d="Investigation active"/></div><div className="two"><Card title="Detection timeline" kicker="ATTACK VOLUME"><ResponsiveContainer width="100%" height={250}><AreaChart data={stats.timeline}><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#6e9dff" stopOpacity=".32"/><stop offset="100%" stopColor="#6e9dff" stopOpacity=".01"/></linearGradient></defs><CartesianGrid stroke="#1c2a40" vertical={false}/><XAxis dataKey="hour" stroke="#647791" tickLine={false} axisLine={false}/><YAxis stroke="#647791" tickLine={false} axisLine={false} allowDecimals={false}/><Tooltip contentStyle={{background:'#0b1422',border:'1px solid #26344e',borderRadius:10,color:'#fff'}}/><Area type="monotone" dataKey="alerts" stroke="#79a4ff" fill="url(#fill)" strokeWidth={2}/></AreaChart></ResponsiveContainer></Card><Card title="Technique distribution" kicker="MITRE ATT&CK"><div className="techs">{stats.techniques.map(x=><div className="tech" key={x.mitre_id}><span><b>{x.mitre_id}</b>{x.name}</span><div><i style={{width:Math.min(100,x.count*20)+'%'}}/></div><em>{x.count}</em></div>)}</div></Card></div><section className="card"><Head kicker="ANALYST QUEUE" title="Active alerts"/><Table alerts={alerts.filter(a=>a.status!=='resolved').slice(0,8)} open={openAlert}/></section><div className="two"><section className="card"><Head kicker="RESPONSE" title="Recent incidents"/>{inc.slice(0,5).map(i=><button className="mini" key={i.id} onClick={()=>openIncident(i.id)}><span><i className={'dot '+i.severity}/><b>{i.incident_id}</b><small>{i.title}</small></span><ChevronRight size={16}/></button>)}</section><section className="card pad"><Head kicker="CONTROL PLANE" title="SOCX status"/><div className="status"><Status x="API"/><Status x="DB"/><Status x="WS"/><Status x="DETECTION"/></div><p className="note">Synthetic lab data is enabled. Ingest your own Wazuh/syslog/Windows events through the API.</p></section></div></div>}
function Alerts({alerts,openAlert}){const[q,setQ]=useState(''),[s,setS]=useState('all'),[st,setSt]=useState('all');let list=useMemo(()=>alerts.filter(a=>{let z=q.toLowerCase();return(!z||[a.title,a.alert_id,a.source_ip,a.username,a.mitre_id].filter(Boolean).some(v=>String(v).toLowerCase().includes(z)))&&(s==='all'||a.severity===s)&&(st==='all'||a.status===st)}),[alerts,q,s,st]);return <div className="stack"><div className="toolbar"><div className="search"><Search size={16}/><input placeholder="Search alerts, IPs, users, MITRE..." value={q} onChange={e=>setQ(e.target.value)}/></div><select value={s} onChange={e=>setS(e.target.value)}>{['all','critical','high','medium','low'].map(x=><option key={x}>{x}</option>)}</select><select value={st} onChange={e=>setSt(e.target.value)}>{['all','new','investigating','resolved','false_positive'].map(x=><option key={x}>{x}</option>)}</select></div><section className="card"><Head kicker="DETECTION ENGINE" title={`${list.length} alert(s)`}/><Table alerts={list} open={openAlert}/></section></div>}
function Incidents({inc,open}){return <div className="stack"><section className="card"><Head kicker="CASE MANAGEMENT" title={`${inc.length} incident(s)`}/><div className="tableWrap"><table><thead><tr><th>Incident</th><th>Severity</th><th>Status</th><th>MITRE</th><th>Assigned</th><th>Created</th><th/></tr></thead><tbody>{inc.map(i=><tr key={i.id}><td><b>{i.incident_id}</b><small>{i.title}</small></td><td><Badge v={i.severity}/></td><td><span className={'status '+i.status}>{i.status}</span></td><td><code>{i.mitre_id||'—'}</code></td><td>{i.assigned_to}</td><td>{fmt(i.created_at)}</td><td><button className="icon" onClick={()=>open(i.id)}><ChevronRight size={16}/></button></td></tr>)}</tbody></table></div>{!inc.length&&<Empty t="No incidents yet. Create one from an alert."/>}</section></div>}
function IOCs({show}){const[q,setQ]=useState(''),[rows,setRows]=useState([]);async function run(){if(!q.trim())return;try{setRows(await api('/api/iocs?q='+encodeURIComponent(q.trim())))}catch(e){show(e.message,'error')}}return <div className="stack"><section className="card pad"><small className="kicker">IOC INTELLIGENCE</small><h2>Investigate an indicator.</h2><p className="muted">Local SOCX observations are returned with an explicit unknown result when no local evidence exists.</p><div className="iocSearch"><div className="search"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&run()} placeholder="10.10.10.50 / domain / SHA256..."/></div><button className="primary" onClick={run}>Investigate</button></div></section><section className="card"><Head kicker="RESULTS" title={`${rows.length} result(s)`}/><div className="iocGrid">{rows.map((r,i)=><div className="ioc" key={i}><div><span className="tag">{r.ioc_type}</span><Badge v={r.risk_score>=90?'critical':r.risk_score>=75?'high':r.risk_score>=50?'medium':'low'}/></div><code>{r.value}</code><small>Reputation: {r.reputation} · Source: {r.source}</small></div>)}{!rows.length&&<Empty t="Search an IP, hash or domain."/>}</div></section></div>}
function AlertDrawer({a,close,refresh,show,create}){const[status,setStatus]=useState(a.status);async function upd(v){try{await api('/api/alerts/'+a.id,{method:'PATCH',body:JSON.stringify({status:v})});setStatus(v);refresh();show('Alert status updated')}catch(e){show(e.message,'error')}}return <Drawer close={close} title="Alert investigation"><Top title={a.title} code={a.alert_id} right={<div className="risk">{a.risk_score}</div>}/><div className="details"><D l="Source IP" v={a.source_ip||'—'}/><D l="Destination IP" v={a.destination_ip||'—'}/><D l="Username" v={a.username||'—'}/><D l="Event" v={a.event_type}/><D l="MITRE" v={(a.mitre_id||'—')+' '+(a.mitre_name||'')}/><D l="Source" v={a.source}/></div><Block t="DESCRIPTION"><p>{a.description}</p></Block><Block t="STATUS"><div className="seg">{['new','investigating','resolved','false_positive'].map(x=><button className={status===x?'sel':''} key={x} onClick={()=>upd(x)}>{x.replace('_',' ')}</button>)}</div></Block><Block t="NORMALIZED DETAILS"><pre>{JSON.stringify(a.details,null,2)}</pre></Block><div className="end"><button className="primary" onClick={create}><Plus size={16}/> Create Incident</button></div></Drawer>}
function IncidentDrawer({i:initial,close,refresh,show}){const[i,setI]=useState(initial),[note,setNote]=useState(''),[en,setEn]=useState(''),[ev,setEv]=useState('');async function reload(){setI(await api('/api/incidents/'+initial.id));refresh()}async function patch(p){try{await api('/api/incidents/'+initial.id,{method:'PATCH',body:JSON.stringify(p)});await reload();show('Incident updated')}catch(e){show(e.message,'error')}}async function addNote(){if(!note.trim())return;await api('/api/incidents/'+i.id+'/notes',{method:'POST',body:JSON.stringify({body:note,author:'SOC Analyst'})});setNote('');reload();show('Note added')}async function addEv(){if(!en.trim()||!ev.trim())return;await api('/api/incidents/'+i.id+'/evidence',{method:'POST',body:JSON.stringify({name:en,value:ev,evidence_type:'IOC',source:'SOC Analyst'})});setEn('');setEv('');reload();show('Evidence added')}return <Drawer close={close} title="Incident response"><Top title={i.title} code={i.incident_id} right={<span className="status open">{i.status}</span>}/><div className="details"><D l="Assigned" v={i.assigned_to}/><D l="MITRE" v={i.mitre_id||'—'}/><D l="Created" v={fmt(i.created_at)}/><D l="Source alert" v={i.alert?.alert_id||'—'}/></div><Block t="WORKFLOW"><div className="seg">{['open','contained','resolved','closed'].map(x=><button className={i.status===x?'sel':''} key={x} onClick={()=>patch({status:x})}>{x}</button>)}</div></Block><Block t="SUMMARY"><textarea value={i.summary} onChange={e=>setI({...i,summary:e.target.value})} onBlur={()=>patch({summary:i.summary})}/></Block><Block t="ANALYST NOTES"><textarea placeholder="Document investigative findings..." value={note} onChange={e=>setNote(e.target.value)}/><button className="secondary" onClick={addNote}><Plus size={14}/> Add note</button>{i.notes.map(n=><div className="entry" key={n.id}><small>{n.author} · {fmt(n.created_at)}</small>{n.body}</div>)}</Block><Block t="EVIDENCE"><input value={en} onChange={e=>setEn(e.target.value)} placeholder="Evidence name"/><input value={ev} onChange={e=>setEv(e.target.value)} placeholder="Evidence value"/><button className="secondary" onClick={addEv}><Plus size={14}/> Add evidence</button>{i.evidence.map(e=><div className="entry" key={e.id}><small>{e.evidence_type} · {e.name}</small><code>{e.value}</code></div>)}</Block><Block t="REPORTS"><div className="reports"><a href={API+`/api/incidents/${i.id}/report.json`} target="_blank"><FileDown size={14}/> JSON</a><a href={API+`/api/incidents/${i.id}/report.html`} target="_blank"><FileDown size={14}/> HTML</a><a href={API+`/api/incidents/${i.id}/report.pdf`} target="_blank"><FileDown size={14}/> PDF</a></div></Block></Drawer>}
function Drawer({title,close,children}){return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&close()}><aside className="drawer"><header><div><small>SOCX</small><h3>{title}</h3></div><button className="icon" onClick={close}><X size={18}/></button></header><div className="drawerBody">{children}</div></aside></div>}
function Top({title,code,right}){return <div className="drawerTop"><div><Badge v="high"/><h2>{title}</h2><code>{code}</code></div>{right}</div>}
function Block({t,children}){return <section className="block"><small className="kicker">{t}</small>{children}</section>}
function D({l,v}){return <div className="detail"><small>{l}</small><span>{v}</span></div>}
function Table({alerts,open}){return <div className="tableWrap"><table><thead><tr><th>Alert</th><th>Severity</th><th>Source</th><th>MITRE</th><th>Risk</th><th>Status</th><th>Time</th><th/></tr></thead><tbody>{alerts.map(a=><tr key={a.id}><td><b>{a.title}</b><small>{a.alert_id}</small></td><td><Badge v={a.severity}/></td><td><span>{a.source_ip||'—'}</span><small>{a.username||'No user'}</small></td><td><code>{a.mitre_id||'—'}</code></td><td><strong>{a.risk_score}</strong></td><td><span className={'status '+a.status}>{a.status.replace('_',' ')}</span></td><td>{fmt(a.created_at)}</td><td><button className="icon" onClick={()=>open(a.id)}><ChevronRight size={16}/></button></td></tr>)}</tbody></table>{!alerts.length&&<Empty t="No matching alerts."/>}</div>}
function Metric({t,v,d}){return <div className="metric"><small>{t}</small><strong>{v}</strong><span>{d}</span></div>}
function Status({x}){return <div className="statusTile"><small>{x}</small><b><i/>ONLINE</b></div>}
function Card({kicker,title,children}){return <section className="card"><Head kicker={kicker} title={title}/>{children}</section>}
function Head({kicker,title}){return <div className="head"><div><small className="kicker">{kicker}</small><h3>{title}</h3></div></div>}
function Badge({v}){return <span className={'badge '+v}>{v}</span>}
function Empty({t}){return <div className="empty"><Network size={16}/>{t}</div>}
function Loading(){return <div className="loading">Loading SOC telemetry...</div>}

createRoot(document.getElementById('root')).render(<App/>);
